export const genres = [
  { id: '1', name: 'Alternative Rock' },
  { id: '2', name: 'Ambient' },
  { id: '3', name: 'Audiobooks' },
  { id: '4', name: 'Business' },
  { id: '5', name: 'Classical' },
  { id: '6', name: 'Comedy' },
  { id: '7', name: 'Country' },
  { id: '8', name: 'Dance & EDM' },
  { id: '9', name: 'Dancehall' },
  { id: '10', name: 'Deep House' },
  { id: '11', name: 'Disco' },
  { id: '12', name: 'Drum & Bass' },
  { id: '13', name: 'Dubstep' },
  { id: '14', name: 'Electronic' },
  { id: '15', name: 'Entertainment' },
  { id: '16', name: 'Folk & Singer-Songwriter' },
  { id: '17', name: 'Hip Hop & Rap' },
  { id: '18', name: 'House' },
  { id: '19', name: 'Indie' },
  { id: '20', name: 'Jazz & Blues' },
  { id: '21', name: 'Latin' },
  { id: '22', name: 'Learning' },
  { id: '23', name: 'Metal' },
  { id: '24', name: 'News & Politics' },
  { id: '25', name: 'Piano' },
  { id: '26', name: 'Pop' },
  { id: '27', name: 'R&B & Soul' },
  { id: '28', name: 'Reggae' },
  { id: '29', name: 'Reggaeton' },
  { id: '30', name: 'Religion & Spirituality' },
  { id: '31', name: 'Rock' },
  { id: '32', name: 'Science' },
  { id: '33', name: 'Soundtrack' },
  { id: '34', name: 'Sports' },
  { id: '35', name: 'Storytelling' },
  { id: '36', name: 'Techno' },
  { id: '37', name: 'Technology' },
  { id: '38', name: 'Trance' },
  { id: '39', name: 'Trap' },
  { id: '40', name: 'Trending Audio' },
  { id: '41', name: 'Trending Music' },
  { id: '42', name: 'Trip Hop' },
  { id: '43', name: 'World' },
];

export const statuses = [
  { id: '1', value: 'Concept' },
  { id: '2', value: 'New band' },
  { id: '3', value: 'Established act' },
];

export const roleTypes = [
  { id: '1', value: 'Vocalist' },
  { id: '2', value: 'Guitarist' },
  { id: '3', value: 'Bassist' },
  { id: '4', value: 'Drummer' },
  { id: '5', value: 'Backing vocalist' },
  { id: '6', value: 'Multi-instrumentalist' },
  { id: '7', value: 'Percussionist' },
  { id: '8', value: 'Synth/Keyboard Player' },
  { id: '9', value: 'Pianist' },
  { id: '10', value: 'Strings (e.g. Violin/Cello)' },
  { id: '11', value: 'Brass (e.g. Trumpet/Trombone)' },
  { id: '12', value: 'Woodwind (e.g. Saxophone/Flute)' },
  { id: '13', value: 'Producer' },
  { id: '14', value: 'Other' },
];

export const roleStatuses = [
  { id: '1', value: 'Currently looking' },
  { id: '2', value: 'Position filled' },
];
